### ISSUE TITLE
Unable to flash my Sonoff ZBdongle-E V1

### ISSUE THREAD

**Issue by ThibLeS-59** [darkxst/silabs-firmware-builder#112]
I'm a beginner, and I can't seem to flash my ZBDongle-E V1. I first tried using the DARKXST site, where it was recognized, but the flashing failed. 

[silabs_flasher (2).log](https://github.com/user-attachments/files/16638559/silabs_flasher.2.log)

Then, I tried using the command line with universal_silabs_flasher, but the installation always ends in an error:
`universal-silabs-flasher --device COM5 --bootloader-reset sonoff flash --firmware "C:\.......`

![image](https://github.com/user-attachments/assets/372c9e54-0e61-44f9-ad2c-5ddd3d5b7150)

**Comment by tl-sl** [comment]
Try without bootloader reset, that seems to be causing the error

```
universal-silabs-flasher --device COM5  --firmware "C:\.......

```

**Comment by ThibLeS-59** [comment]
Yes, i have a same error

**Comment by EmmaPj18** [comment]
I have same issue 
[Log](https://github.com/user-attachments/files/16766257/silabs_flasher.log)

**Comment by EmmaPj18** [comment]
@darkxst Now it can connect and detect the dongle E, but it fails trying to upload the new firmware

![image](https://github.com/user-attachments/assets/577e0def-ea93-430b-aa29-26c8517cd271)

Logs: 
[silabs_flasher (1).log](https://github.com/user-attachments/files/16785097/silabs_flasher.1.log)

**Comment by darkxst** [comment]
> I'm using Brave browser

Probably not, it seems the Windows usb serial driver is causing the dongle to reset when we open serial connection. I will see if I can workaround this second failure also.

**Comment by AlphaArs** [comment]
I'm getting the same problem, just bought the Sonoff ZBDongle-E EFR32MG21.
I installed the  CP210x drivers and on the normal website I did get it detected. But when trying to update or change the firmware I get the error message. I tried both with the silabs builder and the cp-test.

here are the logs:
[patched flasher.log](https://github.com/user-attachments/files/16818469/patched.flasher.log)
[silabs_flasher.log](https://github.com/user-attachments/files/16818474/silabs_flasher.log)

**Comment by EmmaPj18** [comment]
> Probably not, it seems the Windows usb serial driver is causing the dongle to reset when we open serial connection. I will see if I can workaround this second failure also.

@darkxst I tested with the original web patcher on a Macbook and it detects the dongle and I can flash the dongle successfully. As you said, this is a Windows issue with the driver

**Comment by AlphaArs** [comment]
Thats interesting, so If I try to do this with a Linux vm it should work ? @EmmaPj18

**Comment by EmmaPj18** [comment]
> Thats interesting, so If I try to do this with a Linux vm it should work ? @EmmaPj18

Idk but It could work

**Comment by darkxst** [comment]
> so If I try to do this with a Linux vm it should work

yes I believe it will work on Linux. Also if you have a HA box, the Silabs Flasher Addon should work also.

**Comment by madeira3003** [comment]
> > então se eu tentar fazer isso com uma VM Linux deve funcionar
> 
> sim, acredito que funcionará no Linux. Além disso, se você tiver uma caixa HA, o Silabs Flasher Addon também deve funcionar.

Can you help us on how to do this?

**Comment by madeira3003** [comment]
> > so If I try to do this with a Linux vm it should work
> 
> yes I believe it will work on Linux. Also if you have a HA box, the Silabs Flasher Addon should work also.

Can you help us on how to do this?

**Comment by Suffice** [comment]
I'm curious why I received an E V1 dongle when everyone else seems to have an E V2? It seems to be working fine with the latest Ember firmware, aside from my 1st gen Hue bulbs being almost always non-responsive.

I was able to flash my device on Linux, both in the browser and from the terminal.

**Comment by darkxst** [comment]
V1 dongle is actually ZBDongle-P (cc2652). 
V2 dongle is ZBDongle-E.
Sonoff recently changed the USB chip in the ZBDongle-E, and at the time due to production issues, inadvertently flashed some dongles with the USB config file for ZBDongle-P, thus the USB product strings are wrong on these.

**Comment by darkxst** [comment]
Continue in #107
