### ISSUE TITLE
Chrome firmware updater and firmware upload

### ISSUE THREAD

**Issue by mct370770** [darkxst/silabs-firmware-builder#132]
After downloading ZBDonglee firmware "ot-rcp-v2.4.2.0-zbdonglee-460800.gbl" 
and trying to firmware update in the Chrome browser, it throws me an error 
"Failed to parse firmware: pythonerror: traceback ......"

I can fine update to the latest - but I need that specific version.
I tried several other versions also downloaded from your git, same errer.

Anything I am missing?

**Comment by darkxst** [comment]
you need to make sure you are using the raw link from Github and not a html page link

**Comment by mct370770** [comment]
Thanks - solved :-)
