### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MickeyILP** [darkxst/silabs-firmware-builder#138]
Hi, I'm new to the HA family, I've heard about the many benefits of switching to ember so I wanted to try it on my dongle E. Unfortunately it turned out to be impossible on both https://darkxst.github.io/silabs-firmware-builder/ and https://darkxst.github.io/cp-test/

The first page problem is:
![image](https://github.com/user-attachments/assets/e537bf71-266c-4131-8784-7a573053d408)

and the second page:
![image](https://github.com/user-attachments/assets/c7f09005-45d0-434b-8131-6a851240c941)

I tried it on PC with windows

**Comment by darkxst** [comment]
Hi,
  There are issues with windows drivers currently. Try using the HA Silabs Flasher addon instead. There is a hidden field that you can enter a custom URL.

**Comment by MickeyILP** [comment]
> Hi, There are issues with windows drivers currently. Try using the HA Silabs Flasher addon instead. There is a hidden field that you can enter a custom URL.

What URL should i paste? https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.4.4.0-zbdonglee-230400.gbl - this one seems to be not working

**Comment by darkxst** [comment]
You need to use the raw URL in github:
https://github.com/darkxst/silabs-firmware-builder/raw/refs/heads/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.4.4.0-zbdonglee-115200.gbl
https://github.com/darkxst/silabs-firmware-builder/raw/refs/heads/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.4.4.0-zbdonglee-230400.gbl

**Comment by MickeyILP** [comment]
![image](https://github.com/user-attachments/assets/a7de3b76-e90e-4c9e-a4f8-e41d955f811c)
is it done?

**Comment by darkxst** [comment]
yes, no errors so completed successfully

**Comment by MickeyILP** [comment]
Everything seems to be working. Thanks a lot Sir!
