### ISSUE TITLE
I cant flash my Sonoff ZBDongle with web flasher

### ISSUE THREAD

**Issue by R4fte** [darkxst/silabs-firmware-builder#142]
Hey,
I can't flash my Sonoff key with the browser, even though I followed the steps by steps. My key is recognized by the browser, but it tells me that I can't connect and connection failed

The image when we told me to choice a device : 
![image](https://github.com/user-attachments/assets/7dcbbe08-48dc-42be-8503-74616115c780)
The image when its failed : ![image_2024-11-03_141725405](https://github.com/user-attachments/assets/61dc7573-30a6-4f4a-8fca-0b97604db4a4)
The Debug log : [silabs_flasher.log](https://github.com/user-attachments/files/17610542/silabs_flasher.log)

What can I do? Thanks in advance for your answer

**Comment by tootla** [comment]
https://github.com/darkxst/silabs-firmware-builder/issues/107#issuecomment-2436970961

**Comment by tootla** [comment]
@R4fte Hello guy, maybe you can try changing the Windows driver of CP210X , like this : : [https://github.com/darkxst/silabs-firmware-builder/issues/107#issuecomment-2436970961](https://github.com/darkxst/silabs-firmware-builder/issues/107#issuecomment-2436970961)

**Comment by darkxst** [comment]
Closing as this is well covered in #107

**Comment by R4fte** [comment]
Hi back, I Install the driver who u told me but nothing happend, idk what I can do more ?
[silabs_flasher.log](https://github.com/user-attachments/files/17647528/silabs_flasher.log)
![image](https://github.com/user-attachments/assets/688a9e56-aeae-44a4-87fe-6208b3dd7b05)
![image](https://github.com/user-attachments/assets/aa9f4254-c55b-48b6-a79f-23f6b8634614)
![image](https://github.com/user-attachments/assets/a9824d28-4874-4866-bd2d-498d018c30cd)
I follow all step who's written
