### ISSUE TITLE
Connection to ZBDongle-E failed (windows)

### ISSUE THREAD

**Issue by gogo051236** [darkxst/silabs-firmware-builder#147]
Hello,
I am trying to flash a new firmware on my ZBDongle-E but this window appears:
![image](https://github.com/user-attachments/assets/916e2ec5-e151-4724-81fc-56419d8111a6)

I have installed the latest drivers, no program uses the dongle port, can you help me?

Here are the logs:
[silabs_flasher (1).log](https://github.com/user-attachments/files/17721406/silabs_flasher.1.log)

**Comment by tootla** [comment]
@gogo051236  Please try this solution：
[https://github.com/darkxst/silabs-firmware-builder/issues/107#issuecomment-2436970961](https://github.com/darkxst/silabs-firmware-builder/issues/107#issuecomment-2436970961)

**Comment by tootla** [comment]
@darkxst I have an immature idea, I don't know if it can be realized.

If it has been confirmed that the issue is caused by Windows drivers, why not modify the "Connection failed" pop-up message to include the link to the solution in the issue report?

**Comment by darkxst** [comment]
@tootla, the flasher can't detect/know what device is being flashed. So I can't put a device specific error message, and no other device is impacted by this. 

Could put a note on the webpage though, feel free to create a PR for this if you want:
https://github.com/darkxst/silabs-firmware-builder/blob/gh-pages/index.markdown

**Comment by tootla** [comment]
> @tootla, the flasher can't detect/know what device is being flashed. So I can't put a device specific error message, and no other device is impacted by this.
> 
> Could put a note on the webpage though, feel free to create a PR for this if you want: https://github.com/darkxst/silabs-firmware-builder/blob/gh-pages/index.markdown

I'm glad to do it.😄

**Comment by gogo051236** [comment]
> @gogo051236 Please try this solution： [#107 (comment)](https://github.com/darkxst/silabs-firmware-builder/issues/107#issuecomment-2436970961)

It works 🎉, 

thank's
