### ISSUE TITLE
Impossible de flasher ZBdongle E

### ISSUE THREAD

**Issue by n4152394** [darkxst/silabs-firmware-builder#162]
Bonjour,
je suis novice pour mettre a jour ma clef ZBdongle E. je n'arrive pas a changer le firmware via "https://darkxst.github.io/silabs-firmware-builder/" 
![Capture d'écran 2024-12-08 191026](https://github.com/user-attachments/assets/4b3b9956-333b-414d-bb9f-b17343e79e64)
![Capture d'écran 2024-12-08 191140](https://github.com/user-attachments/assets/e1397aab-37e2-4316-8c72-9209b6b8af31)
![Capture d'écran 2024-12-08 191200](https://github.com/user-attachments/assets/1225ed5c-fcf3-4345-a68a-6d03227e91ab)
![Capture d'écran 2024-12-08 191212](https://github.com/user-attachments/assets/f2b26b57-c640-439f-b57b-1a46da8c668f)
et l'installation ne bouge pas .
Pourriez-vous me donner la méthode pour flasher cette clef
merci par avance

**Comment by Fougues** [comment]
meme problème chez moi.
je n'ai pas trouvé de solution.
as tu réussi ?

merci

**Comment by n4152394** [comment]
je viens de remédier à jour la clef 
j'ai mis la clef en mode loader, puis relancer la procédure de mise a jour et cela c'est bien passé pour moi
