### ISSUE TITLE
ZB-GW04 

### ISSUE THREAD

**Issue by RichardPar** [darkxst/silabs-firmware-builder#24]
Hi There,

I have a generic ZB-GW02 v1.2 dongle - flashing the firmware for this device results in 'Secondary is Unresonsive' errors. I go back to my own generic software and it runs. 

Is there perhaps more varieties ?

Thanks
Richard

**Comment by darkxst** [comment]
Which firmware are you using and how did you install it? You probably need to make sure you have the correct baudrate, which should be `230400` for the RCP or Openthread firmwares.

**Comment by RichardPar** [comment]
> Which firmware are you using and how did you install it? You probably need to make sure you have the correct baudrate, which should be `230400` for the RCP or Openthread firmwares.

Sorry,  Ignore me, its was a sheer moment of stupidity.. I had the baud rate too high (the HA Sky Connect pages)

**Comment by RichardPar** [comment]
Closed
