### ISSUE TITLE
Problem with web flasher

### ISSUE THREAD

**Issue by amoutiers** [darkxst/silabs-firmware-builder#29]
Hi,

I've an error using the web flasher, seems missing a Python lib somewhere.

![Capture d’écran 2023-12-11 à 01 20 03](https://github.com/darkxst/silabs-firmware-builder/assets/2652014/18fdee88-76f9-49f6-b3e7-c52a39ef2c28)

Have a nice day,
Best regards

**Comment by darkxst** [comment]
I've logged this upstream, not sure why this is happening
https://github.com/NabuCasa/sl-web-tools/issues/11

**Comment by darkxst** [comment]
This should be fixed now.

**Comment by amoutiers** [comment]
Yes that's ok !
Thanks
