### ISSUE TITLE
Web flasher fails

### ISSUE THREAD

**Issue by V4ler1an** [darkxst/silabs-firmware-builder#30]
When I run the web flasher (Chrome or Edge) it finds the dongle on its serial port ok, gets half way round the connecting progress dial then stops and goes no further. Any idea what this might be? Is there any way to diagnose where it's stopping? I'm using Win 11.  Thanks.

![image](https://github.com/darkxst/silabs-firmware-builder/assets/134781183/fdac847b-4cd3-4a3a-ae9e-da6aad412c62)

![image](https://github.com/darkxst/silabs-firmware-builder/assets/134781183/02dd5965-e1a2-4336-8adf-2c8c00e1c900)

**Comment by 1000sabords** [comment]
Same problem for me (Chrome/w10)

**Comment by azizou016** [comment]
Same problem chrome/edge w11 and macos

**Comment by scobby** [comment]
same problem here under mac os (m2 pro) and windows 11 on a different computer

**Comment by darkxst** [comment]
There is currently an issue with the web flasher due to upstream dependency issue See #29 and https://github.com/NabuCasa/sl-web-tools/issues/11

Should be fixed soon.

**Comment by sormy** [comment]
As an alternative for zbdonglee:

1. Download firmware from
   https://github.com/darkxst/silabs-firmware-builder/tree/main/firmware_builds/zbdonglee
2. Disassemble dongle (take 2 screws of any side), while pressing BOOT button insert into PC/Mac usb port
3. Download SecureCRT for PC/Mac (trial is 30 days):
   https://www.vandyke.com/cgi-bin/releases.php?product=securecrt
4. Follow:
   https://sonoff.tech/wp-content/uploads/2022/11/SONOFF-Zigbee-3.0-USB-dongle-plus-firmware-flashing-.pdf

**Comment by darkxst** [comment]
> As an alternative for zbdonglee:

OR just use `Universal-silabs-flasher`
https://github.com/NabuCasa/universal-silabs-flasher

**Comment by youkorr** [comment]
Hello, is the problem fixed?

**Comment by darkxst** [comment]
Not just yet. Puddly is working on this fix still
https://github.com/NabuCasa/sl-web-tools/pull/12

**Comment by youkorr** [comment]
ok

**Comment by darkxst** [comment]
This should be fixed now.

**Comment by V4ler1an** [comment]
Flashed successfully using the web flasher, thank you!

**Comment by V4ler1an** [comment]
Completed.

**Comment by scobby** [comment]
can not confirm that this is fixed, just tried to flash the Sonoff Dongle-E with the Multipan firmware, didnt work. 

Used Website:
https://dialedin.com.au/blog/sonoff-zbdongle-e-rcp-firmware


This is the output of the console. Its missing a python package SSL:
![SCR-20231214-mtbz](https://github.com/darkxst/silabs-firmware-builder/assets/9264361/d03aa5dd-ef9f-4f67-928a-1021e30b0193)

**Comment by V4ler1an** [comment]
Reopened for you...

**Comment by darkxst** [comment]
Actually that one is related, but I forget to push to fix to the blog. That should be fixed as well now.

**Comment by darkxst** [comment]
These issues should be all fixed now.
