### ISSUE TITLE
web flasher stuck on 87,3%

### ISSUE THREAD

**Issue by iUnstable0** [darkxst/silabs-firmware-builder#32]
Im trying to flash ym ZBDongle-E 

![image](https://github.com/darkxst/silabs-firmware-builder/assets/46888825/a10ef9b4-c695-4ade-9c0d-31d0c15220b5)

Its stuck at 87.3%
do I give it time or reload the page and try again? console said this

![image](https://github.com/darkxst/silabs-firmware-builder/assets/46888825/64153da6-d38e-4eb2-91de-65651c7df4b5)

im flashing OpenThread not multi pan

**Comment by iUnstable0** [comment]
seems like this issue is very random i flashed again with zigbee ezsp firmware and it worked then tried thread and got stuck ahain and when i tried zigbee ezsp it got stuck at around 15% with the same error memory out of bounds

**Comment by darkxst** [comment]
Ive not seen this error before, however if its really getting stuck part way through download suprised it still gets detected in the web flasher when you reload.

Will probably need to report this error upstream on the sl-web-tools repo.

**Comment by iUnstable0** [comment]
yeah im surprised too that the adapter isnt bricked

**Comment by darkxst** [comment]
Can you see the progress messages spamming the console logs? 

the zbdonglee is unbrickable though, you can always  force bootloader with `universal-silabs-flasher` and --sonoff-reset flag, or the internal physical boot button.

**Comment by iUnstable0** [comment]
Im really sorruy for the late reply i didnt get the notification. Nope i cant see the progress logs but updating chrome fixed this issue. Thank you though! 🙏🏻
