### ISSUE TITLE
Build for EmberZNet 6.10.x stack

### ISSUE THREAD

**Issue by TermeHansen** [darkxst/silabs-firmware-builder#33]
I would like to build for the the EmberZNet 6.10.x stack.

As far as I understand right now, that would mean to use the Gecko SDK v3.2 and that is not released on github...
Is this correct, or is it possible with slc to build also for the 6.10.x eznet stack in GSDK 4?

**Comment by darkxst** [comment]
I dont know if things have changed now that SDK 3.x is basically legacy, but previously you needed to purchase and activate an official Silicon Labs Dev kit (WSTK) to get access to the SDK 3.x in Simplicity studio. These kits are not exactly cheap either.

**Comment by darkxst** [comment]
Closing this as can't implement 6.10.x builds in this firmware builder
