### ISSUE TITLE
Zigbee2MQTT not working after update to ncp-uart-hw-v7.4.0.0-zbdonglee-nnn

### ISSUE THREAD

**Issue by derwolff** [darkxst/silabs-firmware-builder#43]
After update Zonoff USB Dongle E to the latest Firmware ncp-uart-hw-v7.4.0.0-zbdonglee-115200, the Zigbee2MQTT Plugin for Home Assistant doesn’t start anymore. It always restart by watchdog.
I have tried both baud rates.
Is there a major change in communication?  
I can't see anything in the log due to existing fault in firmware configuration. This is also shown with the working previous firmware.

[10:38:34] INFO: Starting Zigbee2MQTT...
Assertion failed: Command (setConfigurationValue) returned unexpected state: [object Object]

**Comment by darkxst** [comment]
7.4.0.0 is only supported by ZHA for the moment.  Z2M needs to be patched. More details and links in this 
https://github.com/darkxst/silabs-firmware-builder/issues/40
