### ISSUE TITLE
Connection failed 

### ISSUE THREAD

**Issue by Bblp80** [darkxst/silabs-firmware-builder#49]
I just bought a brand new Sonoff ZBDongle-E and tried to flash it with the WEb Flasher on Chrome. It says: "Connection failed. The running firmware could not be detected." Do I need to do something else before or what can i do?
[silabs_flasher (1).log](https://github.com/darkxst/silabs-firmware-builder/files/14156238/silabs_flasher.1.log)

**Comment by darkxst** [comment]
What OS are you using? It could be permissions errors accessing the dongle?

**Comment by Bblp80** [comment]
Windows 11

**Comment by Bblp80** [comment]
I tried another Laptop and now it works . TY
