### ISSUE TITLE
[REQUEST] EmberZNet Zigbee NCP and OpenThread RCP firmware for RF-BM-MG24B2 (EFR32MG24 based) radio module from RF-Star

### ISSUE THREAD

**Issue by Hedda** [darkxst/silabs-firmware-builder#72]
RF-BM-MG24B2 from RFstar is a new(ish) Silicon Labs EFR32MG24 based radio module designed to be used in different products;

https://www.rfstariot.com/rf-bm-mg24b2-matter-zigbee-openthread-ble-multiprotocol-efr32mg24-module_p106.html

https://www.rfstariot.com/rf-bm-mg24b1-ble5-3-matter-zigbee-thread-efr32mg24-module_p105.html

Note! RF-BM-MG24B2 model only has a PCB trace antenna which is not what most makers of Zigbee Coordinator adapters want.

Very low priority but wondering if there is any interest in Zigbee + OpenThread firmware builds for this EFR32MG24 based board?

I assume that RF-BM-MG24B2 does not ship with Silicon Labs Gecko bootloader pre-flashed as standard so would also need to be made and flashed as well.

This specific radio module is new so not yet used in any complete products you can buy yet as far as I know but similar radio module modules from RFstar (and Ebyte) are used in other Zigbee Coordinator adapters, such USB dongle, Raspberry Pi Shield, and remote network-attached adapters. 

* ZB-GW04 USB dongle (a.k.a. Easyiot stick, a.k.a. CoolKit ZB-GW04)
  * https://shop.dialedin.com.au/products/zb-gw04-v1-2-zigbee-dongle
* TubeZB Gateways
  * https://github.com/tube0013/tube_gateways
  * https://tubeszb.com
* ZigStar Gateways & ZigStar Stick
  * https://github.com/mercenaruss/zigstar_gateways
  * https://zig-star.com/projects/
* Egony Stick & Egony Pi Shield
  * https://github.com/egony/cc2652p_cc1352p_RF-STAR
* CircuitSetup's CC2652P2 USB Coordinator
  * https://circuitsetup.us/product/usb-zigbee-stick-z-stack-coordinator/?v=f003c44deab6

**Comment by darkxst** [comment]
I can't really add the module itself, as different vendors may use different pinouts. Once it shipping on an actual product I can add that.
