### ISSUE TITLE
Builds missing for Elelabs ELx0x3 (ELR023 and ELU013) Zigbee adapters?

### ISSUE THREAD

**Issue by Hedda** [darkxst/silabs-firmware-builder#8]
https://github.com/darkxst/silabs-firmware-builder/tree/main/firmware_builds

Should also be built automatically or? 

https://github.com/darkxst/silabs-firmware-builder/blob/manifestjs/manifests/elelabs-elx0x3.json

PS: More discussion here for reference -> https://github.com/ksjh/silabs-firmware-builder/issues/17

**Comment by darkxst** [comment]
Its not in the main branch just yet. Once I merge the manifest support into main it will be there. Until then the builds in that manifestjs branch should be fine, but haven't been tested.

**Comment by darkxst** [comment]
I have rebased the manifest work and its ready to merge in #23.

**Comment by darkxst** [comment]
These builds are in the main branch now.
